// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CTSERIALIZE_CTSERIALIZE_H_
#define FLATBUFFERS_GENERATED_CTSERIALIZE_CTSERIALIZE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "ccserialization_generated.h"
#include "gdserialization_generated.h"

namespace CTSerialize {

struct MessageHeader;
struct MessageHeaderBuilder;

struct CreateObjects;
struct CreateObjectsBuilder;

struct DeleteObjects;
struct DeleteObjectsBuilder;

struct MoveObjects;
struct MoveObjectsBuilder;

struct LevelSettingChange;
struct LevelSettingChangeBuilder;

struct RotateObject;
struct RotateObjectBuilder;

struct PasteObjects;
struct PasteObjectsBuilder;

struct ModifyObjects;
struct ModifyObjectsBuilder;

struct UpdateFont;
struct UpdateFontBuilder;

struct UpdateSong;
struct UpdateSongBuilder;

struct ChangeGroupID;
struct ChangeGroupIDBuilder;

struct ChangeArt;
struct ChangeArtBuilder;

struct SpeedChange;
struct SpeedChangeBuilder;

struct GameModeChange;
struct GameModeChangeBuilder;

struct RequestLevel;
struct RequestLevelBuilder;

struct ReturnLevelString;
struct ReturnLevelStringBuilder;

struct AdminAction;
struct AdminActionBuilder;

enum MessageBody : uint8_t {
  MessageBody_NONE = 0,
  MessageBody_CreateObjects = 1,
  MessageBody_DeleteObjects = 2,
  MessageBody_MoveObjects = 3,
  MessageBody_LevelSettingChange = 4,
  MessageBody_RotateObject = 5,
  MessageBody_PasteObjects = 6,
  MessageBody_ModifyObjects = 7,
  MessageBody_UpdateFont = 8,
  MessageBody_UpdateSong = 9,
  MessageBody_ChangeGroupID = 10,
  MessageBody_RequestLevel = 11,
  MessageBody_ChangeArt = 12,
  MessageBody_SpeedChange = 13,
  MessageBody_ReturnLevelString = 14,
  MessageBody_GameModeChange = 15,
  MessageBody_AdminAction = 16,
  MessageBody_MIN = MessageBody_NONE,
  MessageBody_MAX = MessageBody_AdminAction
};

inline const MessageBody (&EnumValuesMessageBody())[17] {
  static const MessageBody values[] = {
    MessageBody_NONE,
    MessageBody_CreateObjects,
    MessageBody_DeleteObjects,
    MessageBody_MoveObjects,
    MessageBody_LevelSettingChange,
    MessageBody_RotateObject,
    MessageBody_PasteObjects,
    MessageBody_ModifyObjects,
    MessageBody_UpdateFont,
    MessageBody_UpdateSong,
    MessageBody_ChangeGroupID,
    MessageBody_RequestLevel,
    MessageBody_ChangeArt,
    MessageBody_SpeedChange,
    MessageBody_ReturnLevelString,
    MessageBody_GameModeChange,
    MessageBody_AdminAction
  };
  return values;
}

inline const char * const *EnumNamesMessageBody() {
  static const char * const names[18] = {
    "NONE",
    "CreateObjects",
    "DeleteObjects",
    "MoveObjects",
    "LevelSettingChange",
    "RotateObject",
    "PasteObjects",
    "ModifyObjects",
    "UpdateFont",
    "UpdateSong",
    "ChangeGroupID",
    "RequestLevel",
    "ChangeArt",
    "SpeedChange",
    "ReturnLevelString",
    "GameModeChange",
    "AdminAction",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageBody(MessageBody e) {
  if (::flatbuffers::IsOutRange(e, MessageBody_NONE, MessageBody_AdminAction)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageBody()[index];
}

template<typename T> struct MessageBodyTraits {
  static const MessageBody enum_value = MessageBody_NONE;
};

template<> struct MessageBodyTraits<CTSerialize::CreateObjects> {
  static const MessageBody enum_value = MessageBody_CreateObjects;
};

template<> struct MessageBodyTraits<CTSerialize::DeleteObjects> {
  static const MessageBody enum_value = MessageBody_DeleteObjects;
};

template<> struct MessageBodyTraits<CTSerialize::MoveObjects> {
  static const MessageBody enum_value = MessageBody_MoveObjects;
};

template<> struct MessageBodyTraits<CTSerialize::LevelSettingChange> {
  static const MessageBody enum_value = MessageBody_LevelSettingChange;
};

template<> struct MessageBodyTraits<CTSerialize::RotateObject> {
  static const MessageBody enum_value = MessageBody_RotateObject;
};

template<> struct MessageBodyTraits<CTSerialize::PasteObjects> {
  static const MessageBody enum_value = MessageBody_PasteObjects;
};

template<> struct MessageBodyTraits<CTSerialize::ModifyObjects> {
  static const MessageBody enum_value = MessageBody_ModifyObjects;
};

template<> struct MessageBodyTraits<CTSerialize::UpdateFont> {
  static const MessageBody enum_value = MessageBody_UpdateFont;
};

template<> struct MessageBodyTraits<CTSerialize::UpdateSong> {
  static const MessageBody enum_value = MessageBody_UpdateSong;
};

template<> struct MessageBodyTraits<CTSerialize::ChangeGroupID> {
  static const MessageBody enum_value = MessageBody_ChangeGroupID;
};

template<> struct MessageBodyTraits<CTSerialize::RequestLevel> {
  static const MessageBody enum_value = MessageBody_RequestLevel;
};

template<> struct MessageBodyTraits<CTSerialize::ChangeArt> {
  static const MessageBody enum_value = MessageBody_ChangeArt;
};

template<> struct MessageBodyTraits<CTSerialize::SpeedChange> {
  static const MessageBody enum_value = MessageBody_SpeedChange;
};

template<> struct MessageBodyTraits<CTSerialize::ReturnLevelString> {
  static const MessageBody enum_value = MessageBody_ReturnLevelString;
};

template<> struct MessageBodyTraits<CTSerialize::GameModeChange> {
  static const MessageBody enum_value = MessageBody_GameModeChange;
};

template<> struct MessageBodyTraits<CTSerialize::AdminAction> {
  static const MessageBody enum_value = MessageBody_AdminAction;
};

bool VerifyMessageBody(::flatbuffers::Verifier &verifier, const void *obj, MessageBody type);
bool VerifyMessageBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum AdminActions : int8_t {
  AdminActions_Invalid = 0,
  AdminActions_SteamUserIDBan = 1,
  AdminActions_DisableInteraction = 2,
  AdminActions_Kick = 3,
  AdminActions_MIN = AdminActions_Invalid,
  AdminActions_MAX = AdminActions_Kick
};

inline const AdminActions (&EnumValuesAdminActions())[4] {
  static const AdminActions values[] = {
    AdminActions_Invalid,
    AdminActions_SteamUserIDBan,
    AdminActions_DisableInteraction,
    AdminActions_Kick
  };
  return values;
}

inline const char * const *EnumNamesAdminActions() {
  static const char * const names[5] = {
    "Invalid",
    "SteamUserIDBan",
    "DisableInteraction",
    "Kick",
    nullptr
  };
  return names;
}

inline const char *EnumNameAdminActions(AdminActions e) {
  if (::flatbuffers::IsOutRange(e, AdminActions_Invalid, AdminActions_Kick)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAdminActions()[index];
}

struct MessageHeader FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageHeaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  const ::flatbuffers::Vector<uint8_t> *body_type() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BODY_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *body() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *>(VT_BODY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BODY_TYPE) &&
           verifier.VerifyVector(body_type()) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyVector(body()) &&
           VerifyMessageBodyVector(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

struct MessageHeaderBuilder {
  typedef MessageHeader Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_type(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> body_type) {
    fbb_.AddOffset(MessageHeader::VT_BODY_TYPE, body_type);
  }
  void add_body(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> body) {
    fbb_.AddOffset(MessageHeader::VT_BODY, body);
  }
  explicit MessageHeaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MessageHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MessageHeader>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MessageHeader> CreateMessageHeader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> body_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> body = 0) {
  MessageHeaderBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MessageHeader> CreateMessageHeaderDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *body_type = nullptr,
    const std::vector<::flatbuffers::Offset<void>> *body = nullptr) {
  auto body_type__ = body_type ? _fbb.CreateVector<uint8_t>(*body_type) : 0;
  auto body__ = body ? _fbb.CreateVector<::flatbuffers::Offset<void>>(*body) : 0;
  return CTSerialize::CreateMessageHeader(
      _fbb,
      body_type__,
      body__);
}

struct CreateObjects FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CreateObjectsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJ = 4
  };
  const CTSerialize::GDGameObjectMin *obj() const {
    return GetPointer<const CTSerialize::GDGameObjectMin *>(VT_OBJ);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OBJ) &&
           verifier.VerifyTable(obj()) &&
           verifier.EndTable();
  }
};

struct CreateObjectsBuilder {
  typedef CreateObjects Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obj(::flatbuffers::Offset<CTSerialize::GDGameObjectMin> obj) {
    fbb_.AddOffset(CreateObjects::VT_OBJ, obj);
  }
  explicit CreateObjectsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CreateObjects> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CreateObjects>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CreateObjects> CreateCreateObjects(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<CTSerialize::GDGameObjectMin> obj = 0) {
  CreateObjectsBuilder builder_(_fbb);
  builder_.add_obj(obj);
  return builder_.Finish();
}

struct DeleteObjects FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeleteObjectsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNIQUEIDLIST = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_UNIQUEIDLIST);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UNIQUEIDLIST) &&
           verifier.VerifyVector(uniqueIDList()) &&
           verifier.VerifyVectorOfStrings(uniqueIDList()) &&
           verifier.EndTable();
  }
};

struct DeleteObjectsBuilder {
  typedef DeleteObjects Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uniqueIDList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList) {
    fbb_.AddOffset(DeleteObjects::VT_UNIQUEIDLIST, uniqueIDList);
  }
  explicit DeleteObjectsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeleteObjects> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeleteObjects>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeleteObjects> CreateDeleteObjects(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList = 0) {
  DeleteObjectsBuilder builder_(_fbb);
  builder_.add_uniqueIDList(uniqueIDList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DeleteObjects> CreateDeleteObjectsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList = nullptr) {
  auto uniqueIDList__ = uniqueIDList ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*uniqueIDList) : 0;
  return CTSerialize::CreateDeleteObjects(
      _fbb,
      uniqueIDList__);
}

struct MoveObjects FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MoveObjectsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNIQUEIDLIST = 4,
    VT_POSITIONOFFSET = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_UNIQUEIDLIST);
  }
  const CTSerialize::CCPosI *positionOffset() const {
    return GetStruct<const CTSerialize::CCPosI *>(VT_POSITIONOFFSET);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UNIQUEIDLIST) &&
           verifier.VerifyVector(uniqueIDList()) &&
           verifier.VerifyVectorOfStrings(uniqueIDList()) &&
           VerifyField<CTSerialize::CCPosI>(verifier, VT_POSITIONOFFSET, 4) &&
           verifier.EndTable();
  }
};

struct MoveObjectsBuilder {
  typedef MoveObjects Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uniqueIDList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList) {
    fbb_.AddOffset(MoveObjects::VT_UNIQUEIDLIST, uniqueIDList);
  }
  void add_positionOffset(const CTSerialize::CCPosI *positionOffset) {
    fbb_.AddStruct(MoveObjects::VT_POSITIONOFFSET, positionOffset);
  }
  explicit MoveObjectsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MoveObjects> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MoveObjects>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MoveObjects> CreateMoveObjects(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList = 0,
    const CTSerialize::CCPosI *positionOffset = nullptr) {
  MoveObjectsBuilder builder_(_fbb);
  builder_.add_positionOffset(positionOffset);
  builder_.add_uniqueIDList(uniqueIDList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MoveObjects> CreateMoveObjectsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList = nullptr,
    const CTSerialize::CCPosI *positionOffset = nullptr) {
  auto uniqueIDList__ = uniqueIDList ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*uniqueIDList) : 0;
  return CTSerialize::CreateMoveObjects(
      _fbb,
      uniqueIDList__,
      positionOffset);
}

struct LevelSettingChange FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LevelSettingChangeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SETTINGID = 4
  };
  uint16_t settingID() const {
    return GetField<uint16_t>(VT_SETTINGID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_SETTINGID, 2) &&
           verifier.EndTable();
  }
};

struct LevelSettingChangeBuilder {
  typedef LevelSettingChange Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_settingID(uint16_t settingID) {
    fbb_.AddElement<uint16_t>(LevelSettingChange::VT_SETTINGID, settingID, 0);
  }
  explicit LevelSettingChangeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LevelSettingChange> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LevelSettingChange>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LevelSettingChange> CreateLevelSettingChange(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t settingID = 0) {
  LevelSettingChangeBuilder builder_(_fbb);
  builder_.add_settingID(settingID);
  return builder_.Finish();
}

struct RotateObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RotateObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROTATION = 4,
    VT_ANCHOR = 6,
    VT_UNIQUEIDLIST = 8
  };
  float rotation() const {
    return GetField<float>(VT_ROTATION, 0.0f);
  }
  const CTSerialize::CCPos *anchor() const {
    return GetStruct<const CTSerialize::CCPos *>(VT_ANCHOR);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_UNIQUEIDLIST);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_ROTATION, 4) &&
           VerifyField<CTSerialize::CCPos>(verifier, VT_ANCHOR, 4) &&
           VerifyOffset(verifier, VT_UNIQUEIDLIST) &&
           verifier.VerifyVector(uniqueIDList()) &&
           verifier.VerifyVectorOfStrings(uniqueIDList()) &&
           verifier.EndTable();
  }
};

struct RotateObjectBuilder {
  typedef RotateObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rotation(float rotation) {
    fbb_.AddElement<float>(RotateObject::VT_ROTATION, rotation, 0.0f);
  }
  void add_anchor(const CTSerialize::CCPos *anchor) {
    fbb_.AddStruct(RotateObject::VT_ANCHOR, anchor);
  }
  void add_uniqueIDList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList) {
    fbb_.AddOffset(RotateObject::VT_UNIQUEIDLIST, uniqueIDList);
  }
  explicit RotateObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RotateObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RotateObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RotateObject> CreateRotateObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float rotation = 0.0f,
    const CTSerialize::CCPos *anchor = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList = 0) {
  RotateObjectBuilder builder_(_fbb);
  builder_.add_uniqueIDList(uniqueIDList);
  builder_.add_anchor(anchor);
  builder_.add_rotation(rotation);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RotateObject> CreateRotateObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float rotation = 0.0f,
    const CTSerialize::CCPos *anchor = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList = nullptr) {
  auto uniqueIDList__ = uniqueIDList ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*uniqueIDList) : 0;
  return CTSerialize::CreateRotateObject(
      _fbb,
      rotation,
      anchor,
      uniqueIDList__);
}

struct PasteObjects FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PasteObjectsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNIQUEIDLIST = 4,
    VT_PASTEDSTRING = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_UNIQUEIDLIST);
  }
  const ::flatbuffers::String *pastedString() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PASTEDSTRING);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UNIQUEIDLIST) &&
           verifier.VerifyVector(uniqueIDList()) &&
           verifier.VerifyVectorOfStrings(uniqueIDList()) &&
           VerifyOffset(verifier, VT_PASTEDSTRING) &&
           verifier.VerifyString(pastedString()) &&
           verifier.EndTable();
  }
};

struct PasteObjectsBuilder {
  typedef PasteObjects Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uniqueIDList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList) {
    fbb_.AddOffset(PasteObjects::VT_UNIQUEIDLIST, uniqueIDList);
  }
  void add_pastedString(::flatbuffers::Offset<::flatbuffers::String> pastedString) {
    fbb_.AddOffset(PasteObjects::VT_PASTEDSTRING, pastedString);
  }
  explicit PasteObjectsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PasteObjects> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PasteObjects>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PasteObjects> CreatePasteObjects(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList = 0,
    ::flatbuffers::Offset<::flatbuffers::String> pastedString = 0) {
  PasteObjectsBuilder builder_(_fbb);
  builder_.add_pastedString(pastedString);
  builder_.add_uniqueIDList(uniqueIDList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PasteObjects> CreatePasteObjectsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList = nullptr,
    const char *pastedString = nullptr) {
  auto uniqueIDList__ = uniqueIDList ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*uniqueIDList) : 0;
  auto pastedString__ = pastedString ? _fbb.CreateString(pastedString) : 0;
  return CTSerialize::CreatePasteObjects(
      _fbb,
      uniqueIDList__,
      pastedString__);
}

struct ModifyObjects FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModifyObjectsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNIQUEIDLIST = 4,
    VT_PASTEDSTRING = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_UNIQUEIDLIST);
  }
  const ::flatbuffers::String *pastedString() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PASTEDSTRING);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UNIQUEIDLIST) &&
           verifier.VerifyVector(uniqueIDList()) &&
           verifier.VerifyVectorOfStrings(uniqueIDList()) &&
           VerifyOffset(verifier, VT_PASTEDSTRING) &&
           verifier.VerifyString(pastedString()) &&
           verifier.EndTable();
  }
};

struct ModifyObjectsBuilder {
  typedef ModifyObjects Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uniqueIDList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList) {
    fbb_.AddOffset(ModifyObjects::VT_UNIQUEIDLIST, uniqueIDList);
  }
  void add_pastedString(::flatbuffers::Offset<::flatbuffers::String> pastedString) {
    fbb_.AddOffset(ModifyObjects::VT_PASTEDSTRING, pastedString);
  }
  explicit ModifyObjectsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModifyObjects> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModifyObjects>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModifyObjects> CreateModifyObjects(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList = 0,
    ::flatbuffers::Offset<::flatbuffers::String> pastedString = 0) {
  ModifyObjectsBuilder builder_(_fbb);
  builder_.add_pastedString(pastedString);
  builder_.add_uniqueIDList(uniqueIDList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModifyObjects> CreateModifyObjectsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList = nullptr,
    const char *pastedString = nullptr) {
  auto uniqueIDList__ = uniqueIDList ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*uniqueIDList) : 0;
  auto pastedString__ = pastedString ? _fbb.CreateString(pastedString) : 0;
  return CTSerialize::CreateModifyObjects(
      _fbb,
      uniqueIDList__,
      pastedString__);
}

struct UpdateFont FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateFontBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FONTID = 4
  };
  uint16_t fontID() const {
    return GetField<uint16_t>(VT_FONTID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_FONTID, 2) &&
           verifier.EndTable();
  }
};

struct UpdateFontBuilder {
  typedef UpdateFont Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fontID(uint16_t fontID) {
    fbb_.AddElement<uint16_t>(UpdateFont::VT_FONTID, fontID, 0);
  }
  explicit UpdateFontBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateFont> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateFont>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateFont> CreateUpdateFont(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t fontID = 0) {
  UpdateFontBuilder builder_(_fbb);
  builder_.add_fontID(fontID);
  return builder_.Finish();
}

struct UpdateSong FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateSongBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SONGID = 4
  };
  uint64_t songID() const {
    return GetField<uint64_t>(VT_SONGID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SONGID, 8) &&
           verifier.EndTable();
  }
};

struct UpdateSongBuilder {
  typedef UpdateSong Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_songID(uint64_t songID) {
    fbb_.AddElement<uint64_t>(UpdateSong::VT_SONGID, songID, 0);
  }
  explicit UpdateSongBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateSong> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateSong>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateSong> CreateUpdateSong(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t songID = 0) {
  UpdateSongBuilder builder_(_fbb);
  builder_.add_songID(songID);
  return builder_.Finish();
}

struct ChangeGroupID FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChangeGroupIDBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GROUPID = 4,
    VT_ISADDING = 6,
    VT_UNIQUEIDLIST = 8
  };
  uint32_t groupID() const {
    return GetField<uint32_t>(VT_GROUPID, 0);
  }
  bool isAdding() const {
    return GetField<uint8_t>(VT_ISADDING, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_UNIQUEIDLIST);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_GROUPID, 4) &&
           VerifyField<uint8_t>(verifier, VT_ISADDING, 1) &&
           VerifyOffset(verifier, VT_UNIQUEIDLIST) &&
           verifier.VerifyVector(uniqueIDList()) &&
           verifier.VerifyVectorOfStrings(uniqueIDList()) &&
           verifier.EndTable();
  }
};

struct ChangeGroupIDBuilder {
  typedef ChangeGroupID Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_groupID(uint32_t groupID) {
    fbb_.AddElement<uint32_t>(ChangeGroupID::VT_GROUPID, groupID, 0);
  }
  void add_isAdding(bool isAdding) {
    fbb_.AddElement<uint8_t>(ChangeGroupID::VT_ISADDING, static_cast<uint8_t>(isAdding), 0);
  }
  void add_uniqueIDList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList) {
    fbb_.AddOffset(ChangeGroupID::VT_UNIQUEIDLIST, uniqueIDList);
  }
  explicit ChangeGroupIDBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChangeGroupID> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChangeGroupID>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChangeGroupID> CreateChangeGroupID(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t groupID = 0,
    bool isAdding = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList = 0) {
  ChangeGroupIDBuilder builder_(_fbb);
  builder_.add_uniqueIDList(uniqueIDList);
  builder_.add_groupID(groupID);
  builder_.add_isAdding(isAdding);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ChangeGroupID> CreateChangeGroupIDDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t groupID = 0,
    bool isAdding = false,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList = nullptr) {
  auto uniqueIDList__ = uniqueIDList ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*uniqueIDList) : 0;
  return CTSerialize::CreateChangeGroupID(
      _fbb,
      groupID,
      isAdding,
      uniqueIDList__);
}

struct ChangeArt FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChangeArtBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ChangeArtBuilder {
  typedef ChangeArt Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ChangeArtBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChangeArt> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChangeArt>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChangeArt> CreateChangeArt(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ChangeArtBuilder builder_(_fbb);
  return builder_.Finish();
}

struct SpeedChange FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SpeedChangeBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct SpeedChangeBuilder {
  typedef SpeedChange Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit SpeedChangeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SpeedChange> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SpeedChange>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SpeedChange> CreateSpeedChange(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  SpeedChangeBuilder builder_(_fbb);
  return builder_.Finish();
}

struct GameModeChange FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GameModeChangeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GAMEMODE = 4
  };
  uint8_t gameMode() const {
    return GetField<uint8_t>(VT_GAMEMODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_GAMEMODE, 1) &&
           verifier.EndTable();
  }
};

struct GameModeChangeBuilder {
  typedef GameModeChange Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_gameMode(uint8_t gameMode) {
    fbb_.AddElement<uint8_t>(GameModeChange::VT_GAMEMODE, gameMode, 0);
  }
  explicit GameModeChangeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GameModeChange> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GameModeChange>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GameModeChange> CreateGameModeChange(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t gameMode = 0) {
  GameModeChangeBuilder builder_(_fbb);
  builder_.add_gameMode(gameMode);
  return builder_.Finish();
}

struct RequestLevel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RequestLevelBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct RequestLevelBuilder {
  typedef RequestLevel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit RequestLevelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RequestLevel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RequestLevel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RequestLevel> CreateRequestLevel(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  RequestLevelBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ReturnLevelString FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReturnLevelStringBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNIQUEIDLIST = 4,
    VT_LEVELSTRING = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_UNIQUEIDLIST);
  }
  const ::flatbuffers::String *levelString() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LEVELSTRING);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UNIQUEIDLIST) &&
           verifier.VerifyVector(uniqueIDList()) &&
           verifier.VerifyVectorOfStrings(uniqueIDList()) &&
           VerifyOffset(verifier, VT_LEVELSTRING) &&
           verifier.VerifyString(levelString()) &&
           verifier.EndTable();
  }
};

struct ReturnLevelStringBuilder {
  typedef ReturnLevelString Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uniqueIDList(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList) {
    fbb_.AddOffset(ReturnLevelString::VT_UNIQUEIDLIST, uniqueIDList);
  }
  void add_levelString(::flatbuffers::Offset<::flatbuffers::String> levelString) {
    fbb_.AddOffset(ReturnLevelString::VT_LEVELSTRING, levelString);
  }
  explicit ReturnLevelStringBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReturnLevelString> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReturnLevelString>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReturnLevelString> CreateReturnLevelString(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> uniqueIDList = 0,
    ::flatbuffers::Offset<::flatbuffers::String> levelString = 0) {
  ReturnLevelStringBuilder builder_(_fbb);
  builder_.add_levelString(levelString);
  builder_.add_uniqueIDList(uniqueIDList);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ReturnLevelString> CreateReturnLevelStringDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *uniqueIDList = nullptr,
    const char *levelString = nullptr) {
  auto uniqueIDList__ = uniqueIDList ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*uniqueIDList) : 0;
  auto levelString__ = levelString ? _fbb.CreateString(levelString) : 0;
  return CTSerialize::CreateReturnLevelString(
      _fbb,
      uniqueIDList__,
      levelString__);
}

struct AdminAction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AdminActionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTION = 4,
    VT_USERID = 6,
    VT_TIMEOUTEPOCH = 8,
    VT_REASON = 10
  };
  CTSerialize::AdminActions action() const {
    return static_cast<CTSerialize::AdminActions>(GetField<int8_t>(VT_ACTION, 0));
  }
  uint64_t userId() const {
    return GetField<uint64_t>(VT_USERID, 0);
  }
  uint64_t timeoutEpoch() const {
    return GetField<uint64_t>(VT_TIMEOUTEPOCH, 0);
  }
  const ::flatbuffers::String *reason() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REASON);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_ACTION, 1) &&
           VerifyField<uint64_t>(verifier, VT_USERID, 8) &&
           VerifyField<uint64_t>(verifier, VT_TIMEOUTEPOCH, 8) &&
           VerifyOffset(verifier, VT_REASON) &&
           verifier.VerifyString(reason()) &&
           verifier.EndTable();
  }
};

struct AdminActionBuilder {
  typedef AdminAction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_action(CTSerialize::AdminActions action) {
    fbb_.AddElement<int8_t>(AdminAction::VT_ACTION, static_cast<int8_t>(action), 0);
  }
  void add_userId(uint64_t userId) {
    fbb_.AddElement<uint64_t>(AdminAction::VT_USERID, userId, 0);
  }
  void add_timeoutEpoch(uint64_t timeoutEpoch) {
    fbb_.AddElement<uint64_t>(AdminAction::VT_TIMEOUTEPOCH, timeoutEpoch, 0);
  }
  void add_reason(::flatbuffers::Offset<::flatbuffers::String> reason) {
    fbb_.AddOffset(AdminAction::VT_REASON, reason);
  }
  explicit AdminActionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AdminAction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AdminAction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AdminAction> CreateAdminAction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    CTSerialize::AdminActions action = CTSerialize::AdminActions_Invalid,
    uint64_t userId = 0,
    uint64_t timeoutEpoch = 0,
    ::flatbuffers::Offset<::flatbuffers::String> reason = 0) {
  AdminActionBuilder builder_(_fbb);
  builder_.add_timeoutEpoch(timeoutEpoch);
  builder_.add_userId(userId);
  builder_.add_reason(reason);
  builder_.add_action(action);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AdminAction> CreateAdminActionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    CTSerialize::AdminActions action = CTSerialize::AdminActions_Invalid,
    uint64_t userId = 0,
    uint64_t timeoutEpoch = 0,
    const char *reason = nullptr) {
  auto reason__ = reason ? _fbb.CreateString(reason) : 0;
  return CTSerialize::CreateAdminAction(
      _fbb,
      action,
      userId,
      timeoutEpoch,
      reason__);
}

inline bool VerifyMessageBody(::flatbuffers::Verifier &verifier, const void *obj, MessageBody type) {
  switch (type) {
    case MessageBody_NONE: {
      return true;
    }
    case MessageBody_CreateObjects: {
      auto ptr = reinterpret_cast<const CTSerialize::CreateObjects *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_DeleteObjects: {
      auto ptr = reinterpret_cast<const CTSerialize::DeleteObjects *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_MoveObjects: {
      auto ptr = reinterpret_cast<const CTSerialize::MoveObjects *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_LevelSettingChange: {
      auto ptr = reinterpret_cast<const CTSerialize::LevelSettingChange *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_RotateObject: {
      auto ptr = reinterpret_cast<const CTSerialize::RotateObject *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_PasteObjects: {
      auto ptr = reinterpret_cast<const CTSerialize::PasteObjects *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_ModifyObjects: {
      auto ptr = reinterpret_cast<const CTSerialize::ModifyObjects *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_UpdateFont: {
      auto ptr = reinterpret_cast<const CTSerialize::UpdateFont *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_UpdateSong: {
      auto ptr = reinterpret_cast<const CTSerialize::UpdateSong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_ChangeGroupID: {
      auto ptr = reinterpret_cast<const CTSerialize::ChangeGroupID *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_RequestLevel: {
      auto ptr = reinterpret_cast<const CTSerialize::RequestLevel *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_ChangeArt: {
      auto ptr = reinterpret_cast<const CTSerialize::ChangeArt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_SpeedChange: {
      auto ptr = reinterpret_cast<const CTSerialize::SpeedChange *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_ReturnLevelString: {
      auto ptr = reinterpret_cast<const CTSerialize::ReturnLevelString *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_GameModeChange: {
      auto ptr = reinterpret_cast<const CTSerialize::GameModeChange *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_AdminAction: {
      auto ptr = reinterpret_cast<const CTSerialize::AdminAction *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyMessageBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMessageBody(
        verifier,  values->Get(i), types->GetEnum<MessageBody>(i))) {
      return false;
    }
  }
  return true;
}

inline const CTSerialize::MessageHeader *GetMessageHeader(const void *buf) {
  return ::flatbuffers::GetRoot<CTSerialize::MessageHeader>(buf);
}

inline const CTSerialize::MessageHeader *GetSizePrefixedMessageHeader(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<CTSerialize::MessageHeader>(buf);
}

inline bool VerifyMessageHeaderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<CTSerialize::MessageHeader>(nullptr);
}

inline bool VerifySizePrefixedMessageHeaderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<CTSerialize::MessageHeader>(nullptr);
}

inline void FinishMessageHeaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CTSerialize::MessageHeader> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageHeaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CTSerialize::MessageHeader> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace CTSerialize

#endif  // FLATBUFFERS_GENERATED_CTSERIALIZE_CTSERIALIZE_H_
