#pragma once

#define MOD_LOBBY_ID "chs000.createtogether"
#define MOD_VERSION "v0.5.3"

#define EDITOR_CHANNEL 0
#define CURSOR_CHANNEL 1

#define DEDICATED_EDITOR_PORT 24018
#define DEDICATED_CURSOR_PORT 24019

#define DEDICATED_SERVER_IP 0x7f000001

#define MAX_EDITOR_MESSAGES 128
#define MAX_CURSOR_MESSAGES 64

#define MAX_USERS 8
