include "ccserialization.fbs";
include "gdserialization.fbs";

namespace CTSerialize; 

// Yes this gives out style guideline errors. Cry about it

union MessageBody {
    CreateObjects,
    DeleteObjects,
    MoveObjects,
    LevelSettingChange,
    RotateObjects,
    PasteObjects,
    ModifyObjects,
    ChangeGroupID,
    ModifyObjectAdvancedOptions,
    ModifyObjectBasicOptions,
    ModifyObjectSpecialOptions,
    ChangeDefaultColor,
    RequestLevel,
    ReturnLevelString,
    UpdateFont,
    UpdateSong,
    ChangeArt,
    SpeedChange,
    GameModeChange,
    AdminAction,
    PlayerCursorData,
    RequestForCursors,
    GlobedHandshake
}

table MessageHeader {
    body:MessageBody; 
}

table CreateObjects {
    obj:GDGameObjectMin;
}

table DeleteObjects {
    uniqueIDList:[veryUniqueID];
}

// TODO: Implement a hash-table like optimization for move objects, with posOff being the key and a list of vUID's being the
// value. I Could also make a list of a table [MoveMerge] which has a vUID and a position offset
table MoveObjects {
    moveEntires:[MoveEntry];
}

table LevelSettingChange {
    settingID:uint16;
    spawnGroup:int = null;
}

table RotateObjects {
    rotation:float;
    // Might or might not actually be the anchor point
    anchor:CCPos;
    uniqueIDList:[veryUniqueID];
}

table PasteObjects {
    uniqueIDList:[veryUniqueID];
    pastedString:string;
}

table ModifyObjects {
    uniqueIDList:[veryUniqueID];
    pastedString:string;
}

table ChangeGroupID {
    groupID:uint16;
    isAdding:bool;
    uniqueIDList:[veryUniqueID];
}

// These are the options inside the edit group button
table ModifyObjectAdvancedOptions {
    uniqueIDList:[veryUniqueID];
}

// These are the options inside the edit object button
table ModifyObjectBasicOptions {
    uniqueIDList:[veryUniqueID];

    newText:string; // if exists
    newGroup1Color:uint32; // or something
}

// These are the options inside the edit special button.
// Because I am lazy, these will be using the pastedString method, but may migrate to the
// Other method instead
table ModifyObjectSpecialOptions {
    uniqueIDList:[veryUniqueID];
    pastedString:string;
}

table ChangeDefaultColor {
    colorID:int;
    currentColor:CCColor3B;
    hsv:CCHsvValue;
    blending:bool;
    opacity:float;
    copyOpacity:bool;
    copyColorID:int = null;
}

table RequestLevel { 

}

table ReturnLevelString {
    uniqueIDList:[veryUniqueID];
    levelString:string;
    ctVersion:string;
    isLevelEmpty:bool;
}

table UpdateFont {
    fontID:uint16;
}

table UpdateSong {
    songID:uint64;
}


table ChangeArt {
    artType:ArtType;
    artID:int;
    line:int;
}

// TODO: SpeedChange
table SpeedChange {
    speed:Speed;
}

table GameModeChange {
    gameMode:uint8; // I guess... this dosen't use enums?
}

enum AdminActions : byte { Invalid = 0, SteamUserIDBan, DisableInteraction, Kick }

table AdminAction {
    action:AdminActions;
    userId:uint64; // This might not be unsigned. TODO: Check
    timeoutEpoch:uint64;
    reason:string;
}

table PlayerCursorData {
    playerWave:GDWaveObject;
}

table RequestForCursors {

}

// TODO: Finish
table GlobedHandshake {
    accountID:int;
}

root_type MessageHeader;