name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "deploy"
jobs:
  build:
  
    name: Windows
    runs-on: Windows-latest

    steps:
      - uses: geode-sdk/build-geode-mod@main
        id: build
    

  package:
    name: Package build
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
